spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wichon/spring-boot-petstore.git
          searchPaths: config
#          username: foo
#          password: bar
server:
  port: 8888